### ISSUE TITLE
discussion about difference between re-rank and qb-norm

### ISSUE THREAD

**Issue by onlyonewater** [ioanacroi/qb-norm#5]
Hi, I notice that re-rank [1] as a post-processed technology is very popular in cross-modal retrieval, I think qb-norm is also a re-rank technology. Its implementation is a little different from re-rank. This is my understanding, is it right?

[1] Re-ranking Person Re-identification with k-reciprocal Encoding. CVPR, 2017

**Comment by ioanacroi** [comment]
Hi! 

There are many works that enhance similarity search for retrieval, including re-ranking. QB-Norm focus specifically on tackling the problem of hubness in cross-modal embeddings. Intuitively, QB-Norm aims to scale down the similarity between a video and a query if that video is highly retrieved. This means that combining QB-Norm with a re-ranking method (such as [1]) could potentially further increase the performance.
