### ISSUE TITLE
How do you construct the query bank for MSCOCO image-text retrieval?

### ISSUE THREAD

**Issue by panmianzhi** [ioanacroi/qb-norm#6]
I want to improve the performance on zero-shot image-text retrieval on MSCOCO and only have access to the test split, how can I construct the query bank?

**Comment by vladbogo** [comment]
Hi,

It depends on what are your constraints. From my point of view the options are:
1. generate synthetic queries and use those.
2. use the queries from a different dataset that you have access to.
3. use the test split itself. Be **careful** that this option assumes that you know and have access at inference to the testing distribution which is usually **not** the case in a research scenario and will most likely make your results **not suitable to be compared** with other methods.

Hope this helps!

**Comment by ioanacroi** [comment]
Hi,

Please note that when constructing the querybank you don't need to have access to the text-image pair, you just need the queries (either only the texts for the text-video retrieval task or only the images for the image-text retrieval task). Meaning that there are several ways to construct a querybank even if you don't have access to the training split from a specific dataset, as Vlad pointed out in the previous comment.
